version: 2
updates:
  # Maintain dependencies for the 'web' application
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for the 'bot' application
  - package-ecosystem: "npm"
    directory: "/apps/bot"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
